In [80]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [81]:
##2.Load 20 Newsgroups dataset
from sklearn.datasets import fetch_20newsgroups

In [83]:

"""categories = ['alt.atheism', 'comp.graphics', 'sci.space']
newsgroups_train = fetch_20newsgroups(subset='train', categories=categories, remove=('headers', 'footers', 'quotes'))
newsgroups_test = fetch_20newsgroups(subset='test', categories=categories, remove=('headers', 'footers', 'quotes'))
"""

"categories = ['alt.atheism', 'comp.graphics', 'sci.space']\nnewsgroups_train = fetch_20newsgroups(subset='train', categories=categories, remove=('headers', 'footers', 'quotes'))\nnewsgroups_test = fetch_20newsgroups(subset='test', categories=categories, remove=('headers', 'footers', 'quotes'))\n"

In [86]:
#3.load 20news group train subest
train_subset=pd.read_csv("newsgroups_train.csv")
train_subset

text  target       category
0     From: degroff@netcom.com (21012d)\nSubject: Re...       2      sci.space
1     From: ab@nova.cc.purdue.edu (Allen B)\nSubject...       1  comp.graphics
2     From: healta@saturn.wwc.edu (Tammy R Healy)\nS...       0    alt.atheism
3     From: capelli@vnet.IBM.COM (Ron Capelli)\nSubj...       1  comp.graphics
4     From: henry@zoo.toronto.edu (Henry Spencer)\nS...       2      sci.space
...                                                 ...     ...            ...
1652  From: ab@nova.cc.purdue.edu (Allen B)\nSubject...       1  comp.graphics
1653  From: renes@ecpdsharmony.cern.ch (Rene S. Dutc...       1  comp.graphics
1654  From: xrcjd@resolve.gsfc.nasa.gov (Charles J. ...       2      sci.space
1655  From: dietz@cs.rochester.edu (Paul Dietz)\nSub...       2      sci.space
1656  From: jhwitten@cs.ruu.nl (Jurriaan Wittenberg)...       2      sci.space

[1657 rows x 3 columns]

In [88]:
#4.load 20news group train subest
test_subset=pd.read_csv("newsgroups_test.csv")
test_subset

text  target       category
0     From: mccall@mksol.dseg.ti.com (fred j mccall ...       2      sci.space
1     From: "Changyaw Wang" <wangc@cs.indiana.edu>\n...       1  comp.graphics
2     From: lioness@maple.circa.ufl.edu\nSubject: Te...       1  comp.graphics
3     From: hotopp@ami1.bwi.wec.com (Daniel T. Hotop...       1  comp.graphics
4     From: Ad-Robot@bobsbox.rent.com (Robotic Posti...       1  comp.graphics
...                                                 ...     ...            ...
1097  From: malek@pi.titech.ac.jp (Zidouri Abdelmale...       1  comp.graphics
1098  From: livesey@solntze.wpd.sgi.com (Jon Livesey...       0    alt.atheism
1099  From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...       0    alt.atheism
1100  From: beck@irzr17.inf.tu-dresden.de (Andre Bec...       1  comp.graphics
1101  From: 18084TM@msu.edu (Tom)\nSubject: Billboar...       2      sci.space

[1102 rows x 3 columns]

In [90]:
#5.print all # Load the dataset
newsgroups_train = fetch_20newsgroups(subset='train')

# Print all target labels (categories)
print("All target labels in 20 Newsgroups dataset:")
print(newsgroups_train.target_names)

All target labels in 20 Newsgroups dataset:
['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


In [91]:
#6.prepare subset of categories alt.athessm com.graphics sci.space
from sklearn.datasets import fetch_20newsgroups

# Define the subset of categories
categories = ['alt.atheism', 'comp.graphics', 'sci.space']

# Load the dataset with the selected categories
newsgroups_train = fetch_20newsgroups(subset='train', categories=categories, remove=('headers', 'footers', 'quotes'))
newsgroups_test = fetch_20newsgroups(subset='test', categories=categories, remove=('headers', 'footers', 'quotes'))

# Print the categories to confirm the subset
print("Selected categories:", newsgroups_train.target_names)

# Print some sample data and labels
print("\nSample Text from Training Data:\n", newsgroups_train.data[0])
print("\nCorresponding Label:", newsgroups_train.target[0])


Selected categories: ['alt.atheism', 'comp.graphics', 'sci.space']

Sample Text from Training Data:
 
  I doubt there are good prospects for  a self armoring system
for venus surface conditions (several hundred degrees, very high
pressure of CO2, possibly sulfuric and nitric acids or oxides
but it is a notion to consider for outer planets rs where you might
pick up ices under less extream upper atmosphere conditions buying
deeper penetration.  A nice creative idea, unlikly but worthy of
thinking about.


Corresponding Label: 2


In [93]:
#7 Load the training subset with selected categories
newsgroups_train = fetch_20newsgroups(subset='train', categories=categories, remove=('headers', 'footers', 'quotes'))

# Print the selected categories
print("Loaded categories:", newsgroups_train.target_names)


Loaded categories: ['alt.atheism', 'comp.graphics', 'sci.space']


In [94]:
#8 Load the test subset with selected categories
newsgroups_test = fetch_20newsgroups(subset='test', categories=categories, remove=('headers', 'footers', 'quotes'))

# Print the selected categories
print("Loaded categories:", newsgroups_test.target_names)


Loaded categories: ['alt.atheism', 'comp.graphics', 'sci.space']


In [95]:
#9.print new training set traget names(Lables)
# Define the subset of categories
categories = ['alt.atheism', 'comp.graphics', 'sci.space']

# Load the training subset with selected categories
newsgroups_train = fetch_20newsgroups(subset='train', categories=categories, remove=('headers', 'footers', 'quotes'))

# Print the selected category labels
print("New training set target names (labels):", newsgroups_train.target_names)

# Print unique numerical labels assigned to the categories
print("Numerical labels assigned:", set(newsgroups_train.target))

New training set target names (labels): ['alt.atheism', 'comp.graphics', 'sci.space']
Numerical labels assigned: {0, 1, 2}


In [96]:
#10.print new training data of 5th article
from sklearn.datasets import fetch_20newsgroups

# Define the subset of categories
categories = ['alt.atheism', 'comp.graphics', 'sci.space']

# Load the training subset with selected categories
newsgroups_train = fetch_20newsgroups(subset='train', categories=categories, remove=('headers', 'footers', 'quotes'))

# Print the 5th article's text
print("Training Data - 5th Article:\n")
print(newsgroups_train.data[4])  # Index 4 (since indexing starts at 0)

# Print the corresponding label of the 5th article
print("\nLabel of 5th Article:", newsgroups_train.target[4])
print("Category Name:", newsgroups_train.target_names[newsgroups_train.target[4]])


Training Data - 5th Article:


I don't think you're going to be able to see the differences from a sphere
unless they are greatly exaggerated.  Even the equatorial bulge is only
about 1 part in 300 -- you'd never notice a 1mm error in a 30cm globe --
and the other deviations from spherical shape are much smaller.

Label of 5th Article: 2
Category Name: sci.space


In [97]:
#11.print the shape of data and targets
print("Shape of training data:", len(newsgroups_train.data))

# Print the shape of the targets (number of labels)
print("Shape of training targets:", len(newsgroups_train.target))

Shape of training data: 1657
Shape of training targets: 1657


In [98]:
#12. Print the first 5 filenames
print("First 5 training set filenames:")
print(newsgroups_train.filenames[:5])

# Print the total number of filenames
print("\nTotal number of training files:", len(newsgroups_train.filenames))


First 5 training set filenames:
['/home/user/scikit_learn_data/20news_home/20news-bydate-train/sci.space/60869'
 '/home/user/scikit_learn_data/20news_home/20news-bydate-train/comp.graphics/38633'
 '/home/user/scikit_learn_data/20news_home/20news-bydate-train/alt.atheism/53534'
 '/home/user/scikit_learn_data/20news_home/20news-bydate-train/comp.graphics/38516'
 '/home/user/scikit_learn_data/20news_home/20news-bydate-train/sci.space/61210']

Total number of training files: 1657


In [100]:
#13.by using count vectorizer train data into numerical format considering
from sklearn.feature_extraction.text import CountVectorizer
categories=['alt.atheism', 'comp.graphics','sci.space']
newsgroup_train=fetch_20newsgroups(subset="train",categories=categories,remove=("headers","footers","quotes"))
vectorizer=CountVectorizer()
X_train=vectorizer.fit_transform(newsgroup_train.data)
print("\nSample transformed data (word count vector for first document):")
print(X_train[0].toarray())  # Convert sparse matrix to dense array



Sample transformed data (word count vector for first document):
[[0 0 0 ... 0 0 0]]


In [101]:
#14 Use bernoullNB for training
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

bnb=BernoulliNB()
bnb.fit(X_train,newsgroup_train.target)
y_pred=bnb.predict(X_train)
accuracy= accuracy_score(newsgroup_train.target,y_pred)
print(accuracy)

0.7899818949909475


In [124]:
#15 By using countvectorizer convert test data into numeric format considering only
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer

# Define the subset of categories
categories = ['alt.atheism', 'comp.graphics', 'sci.space']

# Load the training and test subsets
newsgroups_train = fetch_20newsgroups(subset='train', categories=categories, remove=('headers', 'footers', 'quotes'))
newsgroups_test = fetch_20newsgroups(subset='test', categories=categories, remove=('headers', 'footers', 'quotes'))

# Initialize CountVectorizer and fit only on training data
vectorizer = CountVectorizer()
X_train= vectorizer.fit_transform(newsgroups_train.data)  # Fit on training data

# Transform test data using the same vocabulary
X_test = vectorizer.transform(newsgroups_test.data)  # Transform test data

# Print the shape of transformed test data
print("Shape of transformed test data (document-term matrix):", X_test.shape)

# Print some feature names (words converted to features)
print("\nSample feature names:", vectorizer.get_feature_names_out()[:10])

# Print a sample row of the transformed test data
print("\nSample transformed test data (word count vector for first document):")
print(X_test[0].toarray())  # Convert sparse matrix to dense array


Shape of transformed test data (document-term matrix): (1102, 23598)

Sample feature names: ['00' '000' '0000' '00000' '000000' '000005102000' '000062david42'
 '000100255pixel' '00041032' '0004136']

Sample transformed test data (word count vector for first document):
[[0 0 0 ... 0 0 0]]


In [105]:
#16.Predict target labels for testing set
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score

# Define the subset of categories
categories = ['alt.atheism', 'comp.graphics', 'sci.space']

# Load the training and test subsets
newsgroups_train = fetch_20newsgroups(subset='train', categories=categories, remove=('headers', 'footers', 'quotes'))
newsgroups_test = fetch_20newsgroups(subset='test', categories=categories, remove=('headers', 'footers', 'quotes'))

# Convert text data into numerical format
vectorizer = CountVectorizer(binary=True)  # Good for BernoulliNB
X_train = vectorizer.fit_transform(newsgroups_train.data)
X_test = vectorizer.transform(newsgroups_test.data)

# Train the model
bnb = BernoulliNB()
bnb.fit(X_train, newsgroups_train.target)

# Predict on test data
y_pred = bnb.predict(X_test)

# Print predicted vs actual
print("Predicted target labels for test set:\n", y_pred)
print("\nActual target labels:\n", newsgroups_test.target)



Predicted target labels for test set:
 [2 1 1 ... 0 1 2]

Actual target labels:
 [2 1 1 ... 0 1 2]


In [112]:
#17 Find the accuracy score on the test set

# Calculate and print accuracy
accuracy = accuracy_score(newsgroups_test.target, y_pred)
print("BernoulliNB Accuracy on test set:", accuracy)


BernoulliNB Accuracy on test set: 0.6987295825771325


In [113]:
#18.Use TfidfVectorizer instead of count vectorizer and use multinomial NB
from sklearn.datasets import fetch_20newsgroups 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# Define the subset of categories
categories = ['alt.atheism', 'comp.graphics', 'sci.space']

# Load the training and test subsets
newsgroups_train = fetch_20newsgroups(subset='train', categories=categories, remove=('headers', 'footers', 'quotes'))
newsgroups_test = fetch_20newsgroups(subset='test', categories=categories, remove=('headers', 'footers', 'quotes'))

# Convert text data into numerical format using TfidfVectorizer
vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(newsgroups_train.data)  # Fit on training data
X_test_tfidf = vectorizer.transform(newsgroups_test.data)  # Transform test data

# Initialize and train the Multinomial Naïve Bayes classifier
mnb = MultinomialNB()
mnb.fit(X_train_tfidf, newsgroups_train.target)



MultinomialNB()

In [114]:
#19 Find test set accuracy
y_pred = mnb.predict(X_test_tfidf)

# Calculate and print accuracy
accuracy = accuracy_score(newsgroups_test.target, y_pred)
print("Test set accuracy using TfidfVectorizer & MultinomialNB:", accuracy)


Test set accuracy using TfidfVectorizer & MultinomialNB: 0.8620689655172413


In [115]:
#20 Try with avoiding stopwords and repet the same
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# Define the subset of categories
categories = ['alt.atheism', 'comp.graphics', 'sci.space']

# Load the training and test subsets
newsgroups_train = fetch_20newsgroups(subset='train', categories=categories, remove=('headers', 'footers', 'quotes'))
newsgroups_test = fetch_20newsgroups(subset='test', categories=categories, remove=('headers', 'footers', 'quotes'))

# Convert text data into numerical format using TfidfVectorizer (with stopword removal)
vectorizer = TfidfVectorizer(stop_words='english')  # Removes common stopwords like "the", "is", "and"
X_train_tfidf = vectorizer.fit_transform(newsgroups_train.data)  # Fit on training data
X_test_tfidf = vectorizer.transform(newsgroups_test.data)  # Transform test data

# Initialize and train the Multinomial Naïve Bayes classifier
mnb = MultinomialNB()
mnb.fit(X_train_tfidf, newsgroups_train.target)

# Predict target labels for the test set
y_pred = mnb.predict(X_test_tfidf)

# Calculate and print accuracy
accuracy = accuracy_score(newsgroups_test.target, y_pred)
print("Test set accuracy using TfidfVectorizer (with stopword removal) & MultinomialNB:", accuracy)


Test set accuracy using TfidfVectorizer (with stopword removal) & MultinomialNB: 0.8729582577132486


In [116]:
#x=input
#y=categories 